#ifndef GENESIS_CORE_MACROS_H
#define GENESIS_CORE_MACROS_H
#include <math/Vec2.h>
#include <math/Vec3.h>
#include <math/Vec4.h>
#include <cassert>

#define GENESIS_VERTEX_COMPONENT_NONE		(0)
#define GENESIS_VERTEX_COMPONENT_POSITION	(1 << 0)
#define GENESIS_VERTEX_COMPONENT_NORMAL		(1 << 1)
#define GENESIS_VERTEX_COMPONENT_TANGENT	(1 << 2)
#define GENESIS_VERTEX_COMPONENT_BITANGENT	(1 << 3)
#define GENESIS_VERTEX_COMPONENT_TEXCOORD	(1 << 4)
#define GENESIS_VERTEX_COMPONENT_COLOR		(1 << 5)

#define GENESIS_VERTEX_COMPONENT_POSITION_SIZE	sizeof(Vec3)
#define GENESIS_VERTEX_COMPONENT_NORMAL_SIZE	sizeof(Vec3)
#define GENESIS_VERTEX_COMPONENT_TANGENT_SIZE	sizeof(Vec3)
#define GENESIS_VERTEX_COMPONENT_BITANGENT_SIZE	sizeof(Vec3)
#define GENESIS_VERTEX_COMPONENT_TEXCOORD_SIZE	sizeof(Vec2)
#define GENESIS_VERTEX_COMPONENT_COLOR_SIZE		sizeof(Vec4)

#define GENESIS_VERTEX_PRESET_DEFAULT (GENESIS_VERTEX_COMPONENT_POSITION | GENESIS_VERTEX_COMPONENT_NORMAL | GENESIS_VERTEX_COMPONENT_TEXCOORD)
#define GENESIS_VERTEX_PRESET_NORMAL_MAPPED	(GENESIS_VERTEX_PRESET_DEFAULT | GENESIS_VERTEX_COMPONENT_TANGENT | GENESIS_VERTEX_COMPONENT_BITANGENT)

#define GENESIS_ASSERT(condition, msg)\
assert(condition && msg)

#define GENESIS_DISABLE_COPY_AND_MOVE(className)\
	public:\
		className(const className&) = delete;\
		className(className&&) = delete;\
		className& operator =(const className&) = delete;\
		className& operator =(className&&) = delete;

#endif