#ifndef GENESIS_GRAPHICS_MACROS_H
#define GENESIS_GRAPHICS_MACROS_H

// normal rendering

#define SCENE_CONSTANT_BUFFER_SLOT 0
#define SCENE_CONSTANT_BUFFER_NAME "SceneData"

#define CAMERA_CONSTANT_BUFFER_SLOT 1
#define CAMERA_CONSTANT_BUFFER_NAME "CameraData"

#define OBJECT_CONSTANT_BUFFER_SLOT 2
#define OBJECT_CONSTANT_BUFFER_NAME "ObjectData"

#define MATERIAL_CONSTANT_BUFFER_SLOT 3
#define MATERIAL_CONSTANT_BUFFER_NAME "MaterialData"

#define LIGHT_DATA_TEXTURE_SLOT 0
#define DEFAULT_MAX_LIGHTS 128

// post process

#define POST_PROCESSING_EFFECT_CONSTANT_BUFFER_SLOT 0
#define POST_PROCESSING_EFFECT_CONSTANT_BUFFER_NAME "PostProcessData"

#define DEFAULT_TEXTURE_SLOT 0
#define DEFAULT_SAMPLER_STATE_SLOT 0

#endif