#ifndef GENESIS_GRAPHICS_MACROS_H
#define GENESIS_GRAPHICS_MACROS_H

#define CAMERA_CONSTANT_BUFFER_SLOT 0
#define OBJECT_CONSTANT_BUFFER_SLOT 1
#define LIGHT_CONSTANT_BUFFER_SLOT 2
#define MATERIAL_CONSTANT_BUFFER_SLOT 3

#define CAMERA_CONSTANT_BUFFER_NAME "CameraData"
#define OBJECT_CONSTANT_BUFFER_NAME "ObjectData"
#define LIGHT_CONSTANT_BUFFER_NAME "LightData"
#define MATERIAL_CONSTANT_BUFFER_NAME "MaterialData"

#endif